-- Seed data: realistic Italian tile products
-- Based on real Italian tile brands: Marazzi, Ragno, Florim, Ceramiche Caesar

-- Insert demo products with realistic specifications and pricing
INSERT INTO products (
  sku, name, slug, description, category, material, 
  format_width, format_height, thickness, finish,
  color_name, color_hex, style_tags,
  price_per_sqm, cost_per_sqm, min_order_sqm, stock_qty, lead_time_days,
  images, tileable_image_url, certifications, status,
  seo_title, seo_description
) VALUES

-- GRES PORCELLANATO EFFETTO MARMO
(
  'MAR-CAL-001',
  'Marmo Calacatta Gold',
  'marmo-calacatta-gold',
  'Elegante gres porcellanato effetto marmo Calacatta con venature dorate. Superficie lappata di pregio, ideale per ambienti classici e contemporanei. Resistente a macchie e graffi, facile da pulire.',
  'floor',
  'gres',
  600, 600, 10,
  'lappato',
  'Bianco Calacatta', '#F5F5F0',
  ARRAY['marmo', 'classico', 'lusso', 'elegante'],
  52.90, 28.00, 2.0, 450.0, 5,
  '["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800"]'::jsonb,
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200',
  ARRAY['CE', 'UPEC'],
  'active',
  'Gres Porcellanato Effetto Marmo Calacatta Gold | PosaFacile',
  'Piastrelle in gres porcellanato effetto marmo Calacatta Gold con venature dorate. Formato 60x60 cm, finitura lappata. Ideale per pavimenti eleganti.'
),

(
  'MAR-STA-002',
  'Marmo Statuario Bianco',
  'marmo-statuario-bianco',
  'Gres porcellanato che riproduce il pregiato marmo Statuario. Venature grigie delicate su fondo bianco puro. Finitura lucida per un effetto di grande impatto visivo.',
  'floor',
  'gres',
  800, 800, 10.5,
  'glossy',
  'Bianco Statuario', '#FFFFFF',
  ARRAY['marmo', 'classico', 'lusso', 'luminoso'],
  65.00, 35.00, 3.0, 280.0, 7,
  '["https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'UPEC', 'LEED'],
  'active',
  'Gres Statuario Bianco 80x80 Lucido | PosaFacile',
  'Piastrelle gres porcellanato effetto marmo Statuario bianco 80x80 cm lucido. Eleganza classica per interni di pregio.'
),

(
  'MAR-NER-003',
  'Marmo Nero Marquina',
  'marmo-nero-marquina',
  'Sofisticato gres effetto marmo nero con eleganti venature bianche. Perfetto per creare contrasti raffinati in bagni e living moderni.',
  'floor',
  'gres',
  600, 1200, 10,
  'matt',
  'Nero Marquina', '#1A1A1A',
  ARRAY['marmo', 'moderno', 'scuro', 'elegante'],
  58.50, 30.00, 2.0, 180.0, 7,
  '["https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800"]'::jsonb,
  NULL,
  ARRAY['CE'],
  'active',
  'Gres Nero Marquina 60x120 | PosaFacile',
  'Piastrelle gres porcellanato effetto marmo Nero Marquina. Formato 60x120 cm, finitura opaca antiscivolo.'
),

-- GRES EFFETTO LEGNO
(
  'LEG-QUE-001',
  'Rovere Naturale Vero',
  'rovere-naturale-vero',
  'Gres porcellanato effetto legno rovere naturale con texture realistica. Superficie strutturata antiscivolo R10. Ideale per soggiorni, camere e anche bagni.',
  'floor',
  'gres',
  200, 1200, 9.5,
  'textured',
  'Rovere Naturale', '#C4A77D',
  ARRAY['legno', 'naturale', 'caldo', 'tradizionale'],
  38.90, 20.00, 3.0, 650.0, 5,
  '["https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800"]'::jsonb,
  'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=200',
  ARRAY['CE', 'R10'],
  'active',
  'Gres Effetto Legno Rovere 20x120 | PosaFacile',
  'Piastrelle gres porcellanato effetto legno rovere naturale 20x120 cm. Antiscivolo R10, ideale per ogni ambiente.'
),

(
  'LEG-NOC-002',
  'Noce Americano Scuro',
  'noce-americano-scuro',
  'Elegante gres effetto legno noce americano. Tonalità calde e profonde per ambienti accoglienti. Ideale per la posa a spina di pesce.',
  'floor',
  'gres',
  150, 900, 9,
  'matt',
  'Noce Scuro', '#5C4033',
  ARRAY['legno', 'classico', 'caldo', 'elegante'],
  42.00, 22.00, 2.5, 400.0, 5,
  '["https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'R9'],
  'active',
  'Gres Effetto Noce Americano 15x90 | PosaFacile',
  'Piastrelle gres porcellanato effetto noce americano scuro. Formato 15x90 ideale per posa a spina.'
),

(
  'LEG-FRA-003',
  'Frassino Grigio Cenere',
  'frassino-grigio-cenere',
  'Gres porcellanato effetto legno frassino in tonalità grigio cenere. Stile nordico contemporaneo, perfetto per ambienti minimalisti e moderni.',
  'floor',
  'gres',
  200, 1000, 9,
  'matt',
  'Grigio Frassino', '#8B8B7A',
  ARRAY['legno', 'moderno', 'nordico', 'minimalista'],
  35.50, 18.00, 2.0, 520.0, 3,
  '["https://images.unsplash.com/photo-1594007654729-407eedc4be65?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'R9'],
  'active',
  'Gres Frassino Grigio Cenere 20x100 | PosaFacile',
  'Piastrelle gres effetto legno frassino grigio. Design nordico per ambienti contemporanei.'
),

-- GRES EFFETTO PIETRA
(
  'PIE-ARD-001',
  'Ardesia Antracite',
  'ardesia-antracite',
  'Gres porcellanato effetto ardesia in tonalità antracite. Superficie strutturata che riproduce la texture naturale della pietra. Antiscivolo R11, ideale anche per esterni.',
  'outdoor',
  'gres',
  600, 600, 20,
  'textured',
  'Antracite', '#2F2F2F',
  ARRAY['pietra', 'moderno', 'outdoor', 'robusto'],
  45.00, 24.00, 3.0, 350.0, 5,
  '["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'R11', 'spessore 2cm'],
  'active',
  'Gres Effetto Ardesia 60x60 Spessore 2cm | PosaFacile',
  'Piastrelle gres porcellanato effetto ardesia antracite. Spessore 2cm per esterni e carrabili.'
),

(
  'PIE-TRA-002',
  'Travertino Romano',
  'travertino-romano',
  'Gres effetto travertino classico romano. Riproduce fedelmente le sfumature beige e le caratteristiche porosità del travertino naturale.',
  'floor',
  'gres',
  600, 1200, 10,
  'matt',
  'Beige Travertino', '#D4C4A8',
  ARRAY['pietra', 'classico', 'mediterraneo', 'elegante'],
  48.00, 25.00, 2.5, 280.0, 7,
  '["https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'UPEC'],
  'active',
  'Gres Travertino Romano 60x120 | PosaFacile',
  'Piastrelle gres porcellanato effetto travertino romano beige. Formato 60x120 cm per grandi superfici.'
),

(
  'PIE-COT-003',
  'Cotto Toscano Antico',
  'cotto-toscano-antico',
  'Gres effetto cotto toscano fatto a mano. Riproduce le irregolarità e i colori caldi del cotto tradizionale con i vantaggi del gres moderno.',
  'floor',
  'gres',
  300, 300, 10,
  'textured',
  'Rosso Cotto', '#B5651D',
  ARRAY['cotto', 'rustico', 'toscano', 'tradizionale'],
  32.00, 16.00, 3.0, 480.0, 5,
  '["https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'R10'],
  'active',
  'Gres Effetto Cotto Toscano 30x30 | PosaFacile',
  'Piastrelle gres porcellanato effetto cotto toscano antico. Atmosfera rustica con praticità moderna.'
),

-- RIVESTIMENTI BAGNO/CUCINA
(
  'RIV-WHI-001',
  'Soul White Brillante',
  'soul-white-brillante',
  'Rivestimento in ceramica bianco brillante per pareti di bagni e cucine. Superficie lucida facile da pulire, ideale per ambienti luminosi.',
  'wall',
  'ceramic',
  250, 760, 8,
  'glossy',
  'Bianco Brillante', '#FFFFFF',
  ARRAY['moderno', 'luminoso', 'bagno', 'cucina'],
  28.90, 14.00, 2.0, 800.0, 3,
  '["https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800"]'::jsonb,
  NULL,
  ARRAY['CE'],
  'active',
  'Rivestimento Bianco Lucido 25x76 | PosaFacile',
  'Piastrelle rivestimento bianco brillante 25x76 cm. Perfette per bagno e cucina moderna.'
),

(
  'RIV-GRE-002',
  'Nordic Grey Satinato',
  'nordic-grey-satinato',
  'Rivestimento ceramica grigio satinato stile nordico. Finitura morbida al tatto, tonalità neutra perfetta per bagni spa e ambienti rilassanti.',
  'wall',
  'ceramic',
  300, 600, 9,
  'matt',
  'Grigio Nordico', '#9BADB7',
  ARRAY['nordico', 'moderno', 'spa', 'rilassante'],
  34.50, 17.00, 2.0, 520.0, 5,
  '["https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800"]'::jsonb,
  NULL,
  ARRAY['CE'],
  'active',
  'Rivestimento Grigio Nordico 30x60 | PosaFacile',
  'Piastrelle rivestimento grigio satinato stile nordico. Formato 30x60 cm per bagni eleganti.'
),

(
  'RIV-SAG-003',
  'Salvia Verde Opaco',
  'salvia-verde-opaco',
  'Rivestimento ceramica verde salvia opaco. Colore naturale rilassante, molto richiesto per bagni e cucine di tendenza 2024.',
  'wall',
  'ceramic',
  100, 300, 8,
  'matt',
  'Verde Salvia', '#9CAF88',
  ARRAY['naturale', 'tendenza', 'zen', 'organico'],
  36.00, 18.00, 1.5, 380.0, 5,
  '["https://images.unsplash.com/photo-1615874694520-474822394e73?w=800"]'::jsonb,
  NULL,
  ARRAY['CE'],
  'active',
  'Rivestimento Verde Salvia 10x30 | PosaFacile',
  'Piastrelle rivestimento verde salvia opaco. Formato 10x30 cm trend 2024.'
),

-- MOSAICI
(
  'MOS-ESA-001',
  'Mosaico Esagonale Marmo',
  'mosaico-esagonale-marmo',
  'Mosaico esagonale effetto marmo mix bianco e grigio. Foglio da 30x30 cm con esagoni da 5 cm. Perfetto per pavimenti bagno e docce.',
  'mosaic',
  'gres',
  300, 300, 8,
  'matt',
  'Bianco Grigio Mix', '#E8E8E8',
  ARRAY['mosaico', 'esagonale', 'marmo', 'bagno'],
  68.00, 35.00, 1.0, 150.0, 7,
  '["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800"]'::jsonb,
  NULL,
  ARRAY['CE'],
  'active',
  'Mosaico Esagonale Effetto Marmo | PosaFacile',
  'Mosaico esagonale gres porcellanato effetto marmo. Ideale per pavimenti e rivestimenti bagno.'
),

(
  'MOS-PEN-002',
  'Mosaico Penny Round Nero',
  'mosaico-penny-round-nero',
  'Mosaico penny round (tondo) in ceramica nera opaca. Design vintage rivisitato, molto richiesto per bagni dallo stile industrial.',
  'mosaic',
  'ceramic',
  300, 300, 6,
  'matt',
  'Nero Opaco', '#1C1C1C',
  ARRAY['mosaico', 'vintage', 'industrial', 'bagno'],
  55.00, 28.00, 1.0, 200.0, 5,
  '["https://images.unsplash.com/photo-1604709177225-055f99402ea3?w=800"]'::jsonb,
  NULL,
  ARRAY['CE'],
  'active',
  'Mosaico Penny Round Nero Opaco | PosaFacile',
  'Mosaico penny round ceramica nera. Stile vintage industrial per bagni di carattere.'
),

-- OUTDOOR / ESTERNO
(
  'OUT-QUA-001',
  'Quarzite Grigia Outdoor',
  'quarzite-grigia-outdoor',
  'Gres porcellanato effetto quarzite per esterni. Spessore 20mm carrabile, antiscivolo R11 C. Resistente al gelo e agli agenti atmosferici.',
  'outdoor',
  'gres',
  600, 900, 20,
  'textured',
  'Grigio Quarzite', '#6B6B6B',
  ARRAY['pietra', 'outdoor', 'carrabile', 'robusto'],
  55.00, 30.00, 4.0, 300.0, 7,
  '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'R11', 'spessore 2cm', 'carrabile'],
  'active',
  'Gres Quarzite Grigia Outdoor 60x90 2cm | PosaFacile',
  'Piastrelle gres esterni effetto quarzite grigia. Spessore 2cm carrabile, antiscivolo R11.'
),

(
  'OUT-WOO-002',
  'Deck Teak Outdoor',
  'deck-teak-outdoor',
  'Gres porcellanato effetto legno teak per esterni. Spessore 20mm, finitura antiscivolo R11. Perfetto per bordi piscina e terrazze.',
  'outdoor',
  'gres',
  200, 1200, 20,
  'textured',
  'Teak Naturale', '#8B6914',
  ARRAY['legno', 'outdoor', 'piscina', 'terrazza'],
  62.00, 32.00, 3.0, 220.0, 7,
  '["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800"]'::jsonb,
  NULL,
  ARRAY['CE', 'R11', 'spessore 2cm'],
  'active',
  'Gres Effetto Legno Teak Outdoor 20x120 | PosaFacile',
  'Piastrelle gres effetto teak per esterni. Antiscivolo per bordi piscina e terrazze.'
)

ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price_per_sqm = EXCLUDED.price_per_sqm,
  status = EXCLUDED.status,
  updated_at = NOW();
